name: Dummy CI

on:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Check
        run: |
          if stat README.md
          then
            echo 'OK'
          else
            echo 'NG'
          fi
